[[language]]
name = "nix"
formatter.command = "alejandra"
language-servers = ["nil"]

[[language]]
name = "jsonc"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "deno",
]

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "deno",
]

[[language]]
name = "svelte"
formatter = { command = "bun", args = ["prettier", "--parser", "svelte"] }
language-servers = ["tailwindcss-ls", "svelteserver"]

[[language]]
name = "typescript"
formatter = { command = "bun", args = ["prettier", "--parser", "typescript"] }
