name: Build
on:
  push:
    branches: [main]
  pull_request:
jobs:
  kit:
    name: Svelte Kit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
  worker:
    name: Worker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: service
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bunx tsc
