# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  pull_request:
  push:
    branches:
      - main

# env:
#   DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    name: "Build (todo)"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo 'success!'
