# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Static Checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    name: Format JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome lint .
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno fmt --check
  worker-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: service
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun check
  svelte-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
        working-directory: service # doesn't work without this
      - run: bun install --frozen-lockfile
      - run: bun check
  nix-checks:
    name: Nix checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # general/security
      - uses: cachix/install-nix-action@v30
      - run: nix run nixpkgs#gitleaks git -- --verbose
        # checking Nix code
      - run: nix run nixpkgs#alejandra -- --check .
      - run: nix run nixpkgs#deadnix -- --fail .
      - run: nix run nixpkgs#statix -- check .
