# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# TODO: make a test CI

name: Test
on:
  pull_request:
  push:
    branches:
      - main
# env:
#   DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  test:
    name: "Tests (todo)"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo 'success!'
  lockfile:
    name: "Lockfile doesn't have changes"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2
      - run: bun install --frozen-lockfile
