# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10
      - run: bun run test
  lockfile:
    name: "Lockfile doesn't have changes"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10
      - run: bun install --frozen-lockfile
