# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# TODO: make a test CI

name: Test
on:
  pull_request:
  push:
    branches:
      - main
# env:
#   DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  build:
    name: "Tests (todo)"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo 'success!'

  install:
    name: "Lockfile doesn't have changes"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: oven-sh/setup-bun@v2
      - run: just install
